name: my_app_calculadora
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  http: ^0.13.5
  sqflite: ^2.2.6
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  tuple: ^2.0.1
  flutter_simple_calculator: ^2.2.3
  shared_preferences: ^2.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  json_serializable:
  build_runner: 
  bloc_test:

flutter:
  uses-material-design: true
  assets:
    - assets/flags/


